#File /root/.aws was generated by
#aws configure
#Input access-key-id and secret-acces-key of user admin in
#/work/www.credentials/amazon/iam/admin
docker run -it -v /work/www.credentials/amazon/aws-cli/_aws:/root/.aws  greensuisse/aws-cli